### ISSUE TITLE
Add a build heap method.

### ISSUE THREAD

**Issue by oToToT** [luciopaiva/heapify#1]
As we know, we could build a binary heap in O(n) time, are there any method to get this feature in this package?

**Comment by luciopaiva** [comment]
Hey @oToToT, I have just merged your PR, although it is not running in O(n), but in O(n log n). The only way for it to be O(n) would be if the priorities were already ordered, right?

Thanks for the contribution!

**Comment by oToToT** [comment]
Well, I think my implementation is an O(n) algorithm as [wikipedia](https://en.wikipedia.org/wiki/Binary_heap#Building_a_heap) has mentioned.

Btw, thanks for merging my PR.

**Comment by luciopaiva** [comment]
Oh, you're right @oToToT, totally missed it. Very nice!
