### ISSUE TITLE
Size and Capacity properties not on latest npm release

### ISSUE THREAD

**Issue by r0gi** [luciopaiva/heapify#16]
When installing this package via npm, the size and capacity properties recently added in commit [2e13f7d99c1b2f53c3e296ef42b3aa7bed088dfe](https://github.com/luciopaiva/heapify/commit/2e13f7d99c1b2f53c3e296ef42b3aa7bed088dfe) aren't there.

Please update the npm package to match the readme. Thanks!

**Comment by luciopaiva** [comment]
Will look into it as soon as I find some time, @r0gi. Thanks!

**Comment by luciopaiva** [comment]
Hey @r0gi please check v0.3.0, it was just published to npm and contains the missing properties.

Also check [CHANGELOG.md](https://github.com/luciopaiva/heapify/blob/master/CHANGELOG.md) for the complete list of changes.

Thanks!
