### ISSUE TITLE
This is a min heap

### ISSUE THREAD

**Issue by oToToT** [luciopaiva/heapify#2]
From `Upcoming features:`, we can know that this is a min heap implementation. However, I think that it is quite confusing using `highest priority` in `API` section.

**Comment by luciopaiva** [comment]
I called it "highest" on purpose, the idea being that the smallest number in a min heap queue is the highest priority.

But I understand it can generate confusion, so I changed it to say "smallest" instead of "lowest". That should be a bit better.

Thanks!
