### ISSUE TITLE
Adding TypeScript types

### ISSUE THREAD

**Issue by EricCrosson** [luciopaiva/heapify#23]
Hi @luciopaiva, nice package! I found this project through your post on reddit, which included some very nice details, thanks for taking the time to lay everything out so cleanly.

Has anybody brought up adding TypeScript types yet? I'd like to leverage this package in a strongly-typed codebase, which isn't possible to do right now without type-assertions galore.

There are three main approaches to providing types for this package:

1. use TypeScript as the implementation language
  - Upsides:
    - type annotations come for free
    - leverage a fantastic static analysis tool (the type checker) and eliminate space for possible bugs to hide
    - types can never mis-represent behavior (or the TypeScript code wouldn't compile)
  - Downsides:
    - invasive
    - takes time
2. publish types externally in DefinitelyTyped, so users can install the types with `npm i @types/heapify`
  - Downsides:
    - not every version of heapify may be typed, only the versions with a corresponding @types/heapify version
    - takes additional time to manage externally, the DefinitelyTyped publishing process is human-gated and _slow_
    - users must install multiple packages to use this dependency in a strongly-typed environment
3. add a `.d.ts` file to this repo and specify it in `package.json`
  - Upsides:
    - only one package to install for all users
    - every version of heapify can be published with types
  - Downsides:
    - I've never created a harness to test that types aren't out of date/stale, although I'm sure it can be done
    - requires manually updating types 
    - types could mis-represent behavior (since it's as loose a contract as documentation w/o being checked by a compiler)

The right path forward will be dependent on several factors, including
- your willingness to type this project internally (else 2 is the only option)
- your familiarity with TypeScript
- the amount of expected churn in the public API

**Comment by EricCrosson** [comment]
After poking around the source, there's not very much code (well done!) so a port to TS could be a swift endeavor

**Comment by luciopaiva** [comment]
Hey @EricCrosson!

I would vote against option 1 because it would prevent usage on projects that do not use TS. I'd prefer to keep Heapify as vanilla and unopinionated as possible.

I would be ok with option 2 because it's totally non-invasive, although I agree it would require someone keeping it with every new version released.

Option 3 would also be fine, I guess. It shouldn't be too difficult to keep it as the API evolves.

Let me know if you want to try option 3 and I'll be glad to review your PR.

Thanks for taking the time to open the discussion and elaborate the options so well.

**Comment by luciopaiva** [comment]
> I would vote against option 1 because it would prevent usage on projects that do not use TS. I'd prefer to keep Heapify as vanilla and unopinionated as possible.

Nevermind what I said above. Of course it wouldn't force users to adopt TypeScript as well, since they'd be using transpiled code. Nevertheless, if I were to start adopting TS now, I'd start with options 2 or 3 and then later give some thought about option 1 (when I have the time).

**Comment by QuentinLemCode** [comment]
Have you started working on a .d.ts file ?

**Comment by QuentinLemCode** [comment]
Here is the .d.ts file for the master branch
https://gist.github.com/QuentinLemCode/f07654289dafde751e576ed271243ebb

@luciopaiva can you add it please

**Comment by luciopaiva** [comment]
Hey @QuentinLemCode, thanks for your contribution.

There you go: https://www.npmjs.com/package/heapify/v/0.5.0

I made 3 small adjustments: `bubbleUp()`, `buddleDown()` and `removePoppedElement()` are supposed to be private methods, so I changed their visibilities accordingly. All the rest looked good to me.
