### ISSUE TITLE
remove arbitrary element [question]

### ISSUE THREAD

**Issue by llaenowyd** [luciopaiva/heapify#35]
I think the only way to remove entries from the `Heapify` queue is `pop`.

If so is the following approach optimal?

Could you please respond to or verify the inline remarks?

```js
  const popEntry = () => {
    const priority = queue.peekPriority()
    const key = queue.pop()
    return { priority, key }
  }

  const poppedEntries = []

  // alternating peek/pop -> this loop is O(n) ?
  for (let entry = popEntry(); !removalPredicate(entry); entry = popEntry())
    poppedEntries.push(entry)

  // this loop is O(n lg n) ?
  //   - although ordering info is preserved
  //   - i.e. if poppedEntries were reverse iterated this loop would be doing push-min
  //   - it doesn't seem possible on the Heapify API to use this fact, but is that
  //       an API limitation or due to innate heap mechanics?
  for (let {key, priority} of poppedEntries)
    queue.push(key, priority)
```

**Comment by luciopaiva** [comment]
Hey @llaenowyd,

> I think the only way to remove entries from the `Heapify` queue is `pop`.

That's correct.

>   // alternating peek/pop -> this loop is O(n) ?
>   for (let entry = popEntry(); !removalPredicate(entry); entry = popEntry())
>     poppedEntries.push(entry)

No. Popping a single element from a heap costs O(log n) because the heap property must be maintained, so popping all elements (what your for loop is effectively doing) results in O(n log n).

>   // this loop is O(n lg n) ?
>   //   - although ordering info is preserved
>   //   - i.e. if poppedEntries were reverse iterated this loop would be doing push-min
>   //   - it doesn't seem possible on the Heapify API to use this fact, but is that
>   //       an API limitation or due to innate heap mechanics?
>   for (let {key, priority} of poppedEntries)
>     queue.push(key, priority)
> ```

Actually, in your specific example, this loop is effectively O(n) because `poppedEntries` is already sorted from lowest to highest priority, so each push becomes a constant operation since there's no need to bubble elements up or down the heap - they are already pushed in their resting position. In the general case, though, push()ing costs O(log n) for each element, so adding n elements would cost a total of O(n log n).

However, it's worth mentioning that if you need to insert n elements and they are not already sorted, you can still achieve O(n) by building a new queue and passing them all at once. Check this [example](https://github.com/luciopaiva/heapify/blob/master/test/heapify.mjs#L28).

**Comment by llaenowyd** [comment]
Thanks very much!
