### ISSUE TITLE
Wrong behavior on v0.4.0

### ISSUE THREAD

**Issue by tuner** [luciopaiva/heapify#40]
Hi,

The optimizations in v0.4.0 seem to have introduces erroneous behavior. My k-way merge algoritm, which produces nicely ordered results with v0.3.0, seems to be broken on v0.4.0. 

Here's a snippet that reproduces the behavior for both the old and new versions:
https://codepen.io/tuner-the-typescripter/pen/mdMXQdE

**Comment by luciopaiva** [comment]
Hey @tuner,

Thanks for reporting this. There was indeed a bug introduced in 0.4.0, which is now [fixed](https://github.com/luciopaiva/heapify/blob/master/test/heapify.mjs#L224) in 0.4.1.
